### ISSUE TITLE
ImportError: cannot import name 'SiglipVisionModel' from 'transformers'

### ISSUE THREAD

**Issue by formulake** [gokayfem/VLM_nodes#46]
I get this error while trying to run the MCLLAVA node after recent updates.

> !!! Exception during processing !!!
> Traceback (most recent call last):
>   File "F:\Tools\ComfyUI\execution.py", line 148, in recursive_execute
>     obj = class_def()
>   File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\mcllava.py", line 56, in __init__
>     self.predictor = MCLLaVAModelPredictor()
>   File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\mcllava.py", line 23, in __init__
>     self.model = AutoModelForCausalLM.from_pretrained(self.model_path, torch_dtype=torch.float16, trust_remote_code=True).to(self.device)
>   File "F:\Tools\ComfyUI\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 526, in from_pretrained
>     config, kwargs = AutoConfig.from_pretrained(
>   File "F:\Tools\ComfyUI\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1091, in from_pretrained
>     config_class = get_class_from_dynamic_module(
>   File "F:\Tools\ComfyUI\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
>     return get_class_in_module(class_name, final_module.replace(".py", ""))
>   File "F:\Tools\ComfyUI\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
>     module = importlib.import_module(module_path)
>   File "C:\Users\kunal\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\kunal\.cache\huggingface\modules\transformers_modules\files_for_mcllava\modeling_llava.py", line 11, in <module>
>     from transformers import PreTrainedModel, SiglipVisionModel
> ImportError: cannot import name 'SiglipVisionModel' from 'transformers' (F:\Tools\ComfyUI\venv\lib\site-packages\transformers\__init__.py)
>

**Comment by gokayfem** [comment]
update transformers library if you want to use this i think

click install pip packages inside ComfyUI Manager

write ```transformers>=4.38.2```

then restart ComfyUI

![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/00e5c070-49eb-4460-bc4a-9a081bf6bf95)

**Comment by formulake** [comment]
> update transformers library if you want to use this i think
> 
> click install pip packages inside ComfyUI Manager
> 
> write `transformers>=4.38.2`
> 
> then restart ComfyUI


Thanks for the fix. I did this but unfortunately it seems to conflict with the transformers version requirement of other nodes. I guess that's the down-side to having a lot of nodes :) 

Appreciate you lending a hand.

**Comment by gokayfem** [comment]
yes i wish there is different environments for each node but, this is the way for now.

**Comment by YZPKQ02** [comment]
> yes i wish there is different environments for each node but, this is the way for now.

Successfully solved the problem
