### ISSUE TITLE
Kosmos 2.5 released - Possible to add support for it?

### ISSUE THREAD

**Issue by CCpt5** [gokayfem/VLM_nodes#85]
Hello,

Thanks for your time and effort on this node!

I noticed that Microsoft quietly dropped the model for Kosmos 2.5 yesterday here: https://github.com/microsoft/unilm/tree/master/kosmos-2.5
https://huggingface.co/microsoft/kosmos-2.5

The paper was published last September: https://arxiv.org/abs/2309.11419

Curious if you have plans to make it usable with this node or for ComfyUI in any fashion?

Thanks for any info!!

**Comment by gokayfem** [comment]
there are a lot of new vlms released in 2 months, im planning to add some of them, mantis, llava lama3, llava phi3, idefics 8b, deepseekvl, qwen vl, internlm 4khd etc..
